### ISSUE TITLE
سوال زنجیره کوئرا

### ISSUE THREAD

**Issue by pouyarzh** [AMK9978/ProgrammingProblems#16]
سلام
من سوال زنجیره توی کوئرا رو خواستم حل کنم واقعا ذهنمو درگیر کرده کسی راه حلی براش داره 
من از __call__ استفاده کردم که Magic method در پایتون میشه اگه اشتباه نکنم
class Chain(str):
    def __call__(self, param):
        return Chain(self + ' ' + param)

    pass

print(Chain('1')('2')('3')('4'))
که نمیتونم بدون تعیین ارث بری کلاس بهش پارامتر پاس بدم یا کلاسی از نوع str int و float تعریف کنم

**Comment by AMK9978** [comment]
متاسفانه خیلی خیلی دیر، بیشتر از ۲ سال بعد من ایشو رو دیدم. فکر کنم تا حالا حتما مساله ات حل شده باشه :)
متاسفم که نتونستم رسیدگی کنم. احتمالا خود داک پایتون با مثال این سینتکس رو توضیح بده وگرنه ازنظر الگوریتمی فرق خاصی برای حل اون سوال نمیکنه.
